import argparse
import json
import re
from pathlib import Path
from typing import Any

from flashrag.dataset import Dataset, Item
from flashrag.evaluator import Evaluator

ANSWER_TAG_PATTERN = re.compile(
    r"<answer>(.*?)</answer>", flags=re.DOTALL | re.IGNORECASE
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Evaluate main.py jsonlines outputs with FlashRAG"
    )
    parser.add_argument(
        "--result_file",
        type=str,
        required=True,
        help="Path to jsonlines generated by main.py",
    )
    parser.add_argument(
        "--dataset_path",
        type=str,
        required=False,
    )
    parser.add_argument("--debug", action="store_true")
    parser.add_argument(
        "--dataset_name",
        type=str,
        default="main_output_eval",
        help="Dataset name used by FlashRAG evaluator",
    )
    return parser


def read_jsonlines(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at line {line_no}: {exc}") from exc
            records.append(obj)
    return records


def write_jsonlines(path: Path, records: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")


def extract_answer_tag(text: str) -> str:
    match = ANSWER_TAG_PATTERN.search(text)
    if not match:
        return ""
    return match.group(1).strip()


def extract_answer(record: dict[str, Any]) -> str:
    pred = str(record.get("predicted_answer_in_tag", "") or "").strip()
    if pred:
        return pred

    model_output = str(record.get("model_output", "") or "")
    extracted = extract_answer_tag(model_output)
    if extracted:
        return extracted

    pipeline_result = record.get("pipeline_result", {})
    if isinstance(pipeline_result, dict):
        final_answer = str(pipeline_result.get("final_answer", "") or "")
        extracted_final = extract_answer_tag(final_answer)
        if extracted_final:
            return extracted_final
        if final_answer.strip():
            return final_answer.strip()

    return model_output.strip()


def main() -> None:
    args = build_parser().parse_args()
    result_file = Path(args.result_file).resolve()
    if not result_file.exists():
        raise FileNotFoundError(f"result_file not found: {result_file}")

    save_dir = result_file.parent
    raw_records = read_jsonlines(result_file)
    if not raw_records:
        raise ValueError("result_file is empty")

    predictions: list[str] = []

    dataset_path = args.dataset_path
    dataset_name = args.dataset_name
    dataset: Dataset = Dataset(
        config={"dataset_name": dataset_name},
        dataset_path=str(dataset_path),
        sample_num=len(raw_records),
    )

    if args.debug:
        import debugpy

        debugpy.listen(9999)
        print("waiting for debugger attaching")
        debugpy.wait_for_client()
        print("debugger attached")
    item: Item
    for record, item in zip(raw_records, dataset.data):
        prediction = extract_answer(record)
        predictions.append(prediction)
        item.upate_item(record)

    dataset.pred = predictions

    evaluator = Evaluator(
        config={
            "dataset_name": dataset_name,
            "save_dir": str(save_dir),
            "metrics": [
                "f1",
                "em",
                "recall",
                "precision",
                "acc",
                "cover_em_1",
                "cover_em_2",
            ],
            "save_metric_score": True,
            "save_intermediate_data": True,
            "save_data_format": "jsonlines",
            "saved_jsonlines_name": f"{dataset_name}.jsonl",
        }
    )
    result_dict = evaluator.evaluate(dataset)
    metric_json_path = save_dir / "metrics.json"
    with metric_json_path.open("w", encoding="utf-8") as f:
        json.dump(result_dict, f, ensure_ascii=False, indent=2)

    print(f"Loaded result file: {result_file}")
    print(f"Saved metrics to: {metric_json_path}")
    print(result_dict)


if __name__ == "__main__":
    main()
